// mockData.js — Offline-safe mock data matching API response shapes

const MOCK_NODE_TYPES = [
  {
    type: "decision_system.trigger_manual",
    label: "Manual Trigger",
    description: "Start a workflow manually",
    icon: "⚡",
    color: "#3b82f6",
    categories: ["trigger"],
    config_schema: { type: "object", properties: {} },
    input_schema: { type: "object", properties: {} },
    output_schema: { type: "object", properties: { triggered: { type: "boolean" } } },
  },
  {
    type: "decision_system.input_text",
    label: "Input Text",
    description: "Provide text input for the workflow",
    icon: "✏️",
    color: "#14b8a6",
    categories: ["trigger"],
    config_schema: {
      type: "object",
      properties: {
        text: { type: "string", title: "Text", default: "" },
        label: { type: "string", title: "Label", default: "Enter text" },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: { type: "object", properties: { text: { type: "string" } } },
  },
  {
    type: "decision_system.retrieve",
    label: "Retrieve Evidence",
    description: "Retrieve documents from the vector store",
    icon: "🔍",
    color: "#f59e0b",
    categories: ["data"],
    config_schema: {
      type: "object",
      properties: {
        collection: { type: "string", title: "Collection", default: "company_docs" },
        top_k: { type: "integer", title: "Top K", default: 5 },
      },
    },
    input_schema: { type: "object", properties: { query: { type: "string" } } },
    output_schema: { type: "object", properties: { chunks: { type: "array" } } },
  },
  {
    type: "decision_system.technical_analyst",
    label: "Technical Analyst",
    description: "Analyze technical data and system information",
    icon: "🔧",
    color: "#8b5cf6",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake", "nvidia_nim", "ollama"] },
      },
    },
    input_schema: { type: "object", properties: { data: { type: "object" } } },
    output_schema: { type: "object", properties: { analysis: { type: "object" } } },
  },
  {
    type: "decision_system.risk_analyst",
    label: "Risk Analyst",
    description: "Analyze risks and vulnerabilities",
    icon: "🛡️",
    color: "#a855f7",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake", "nvidia_nim", "ollama"] },
      },
    },
    input_schema: { type: "object", properties: { data: { type: "object" } } },
    output_schema: { type: "object", properties: { risks: { type: "array" } } },
  },
  {
    type: "decision_system.extract_claims",
    label: "Extract Claims",
    description: "Extract claims from analysis output",
    icon: "📌",
    color: "#7c3aed",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        supported_types: { type: "array", title: "Supported Types", items: { type: "string" } },
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake", "nvidia_nim", "ollama"] },
      },
    },
    input_schema: { type: "object", properties: { text: { type: "string" } } },
    output_schema: { type: "object", properties: { claims: { type: "array" } } },
  },
  {
    type: "decision_system.verify_claims",
    label: "Verify Claims",
    description: "Verify extracted claims against evidence",
    icon: "✅",
    color: "#9333ea",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake", "nvidia_nim", "ollama"] },
      },
    },
    input_schema: { type: "object", properties: { claims: { type: "array" } } },
    output_schema: { type: "object", properties: { verified: { type: "array" } } },
  },
  {
    type: "decision_system.write_report",
    label: "Write Report",
    description: "Generate a decision report from verified claims",
    icon: "📝",
    color: "#6d28d9",
    categories: ["output"],
    config_schema: {
      type: "object",
      properties: {
        format: { type: "string", title: "Format", default: "markdown", enum: ["markdown", "json"] },
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake", "nvidia_nim", "ollama"] },
      },
    },
    input_schema: { type: "object", properties: { claims: { type: "array" } } },
    output_schema: { type: "object", properties: { report: { type: "object" } } },
  },
  {
    type: "decision_system.extract_graph",
    label: "Extract Graph",
    description: "Extract entities and relationships from documents",
    icon: "🕸️",
    color: "#d97706",
    categories: ["data"],
    config_schema: { type: "object", properties: {} },
    input_schema: { type: "object", properties: { chunks: { type: "array" } } },
    output_schema: { type: "object", properties: { graph: { type: "object" } } },
  },
  {
    type: "decision_system.profile_data",
    label: "Profile Data",
    description: "Profile local CSV data files",
    icon: "📋",
    color: "#ea580c",
    categories: ["data"],
    config_schema: {
      type: "object",
      properties: {
        catalog_path: { type: "string", title: "Catalog Path", default: "company_data" },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: { type: "object", properties: { profiles: { type: "array" } } },
  },
  {
    type: "decision_system.map_ontology",
    label: "Map Ontology",
    description: "Map data profiles to ontology concepts",
    icon: "🧩",
    color: "#7e22ce",
    categories: ["output"],
    config_schema: { type: "object", properties: {} },
    input_schema: { type: "object", properties: { profiles: { type: "array" } } },
    output_schema: { type: "object", properties: { ontology: { type: "object" } } },
  },
  {
    type: "decision_system.detect_patterns",
    label: "Detect Patterns",
    description: "Run pattern and vulnerability detection",
    icon: "🔮",
    color: "#a21caf",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        severity_threshold: {
          type: "string", title: "Severity Threshold", default: "low",
          enum: ["low", "medium", "high", "critical"],
        },
      },
    },
    input_schema: { type: "object", properties: { profiles: { type: "array" } } },
    output_schema: { type: "object", properties: { insights: { type: "array" } } },
  },
  {
    type: "decision_system.war_room",
    label: "Run War Room",
    description: "Run the multi-role analysis protocol",
    icon: "🏛️",
    color: "#6b21a8",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        question: { type: "string", title: "Question", description: "Business question", default: "" },
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake", "nvidia_nim", "ollama"] },
      },
    },
    input_schema: { type: "object", properties: { question: { type: "string" } } },
    output_schema: { type: "object", properties: { war_room_run: { type: "object" } } },
  },
  {
    type: "decision_system.filter",
    label: "Filter",
    description: "Filter data based on conditions",
    icon: "🧪",
    color: "#6b7280",
    categories: ["flow"],
    config_schema: {
      type: "object",
      properties: {
        field: { type: "string", title: "Field to check", default: "" },
        operator: {
          type: "string", title: "Operator", default: "exists",
          enum: ["exists", "equals", "not_equals", "greater_than", "less_than"],
        },
        value: { type: "string", title: "Value", default: "" },
      },
    },
    input_schema: { type: "object", properties: { data: { type: "array" } } },
    output_schema: { type: "object", properties: { filtered: { type: "array" } } },
  },
  {
    type: "decision_system.merge",
    label: "Merge",
    description: "Merge multiple data sources",
    icon: "🔀",
    color: "#4b5563",
    categories: ["flow"],
    config_schema: {
      type: "object",
      properties: {
        strategy: {
          type: "string", title: "Strategy", default: "merge",
          enum: ["merge", "concat"],
        },
      },
    },
    input_schema: { type: "object", properties: { sources: { type: "array" } } },
    output_schema: { type: "object", properties: { merged: { type: "object" } } },
  },
  {
    type: "decision_system.code",
    label: "Code",
    description: "Execute a Python snippet",
    icon: "💻",
    color: "#374151",
    categories: ["flow"],
    config_schema: {
      type: "object",
      properties: {
        source: { type: "string", title: "Python Code", default: "# output = ...", format: "textarea" },
      },
    },
    input_schema: { type: "object", properties: { data: { type: "object" } } },
    output_schema: { type: "object", properties: { result: { type: "object" } } },
  },
  // --- Phase 4: Schedule Trigger Nodes ---
  {
    type: "decision_system.trigger_cron",
    label: "Cron Trigger",
    description: "Trigger a workflow on a cron schedule",
    icon: "🕐",
    color: "#6366f1",
    categories: ["trigger"],
    config_schema: {
      type: "object",
      properties: {
        expression: {
          type: "string", title: "Cron Expression",
          default: "0 9 * * 1",
          description: "Five-field cron expression (minute hour day-of-month month day-of-week)",
        },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: {
      type: "object",
      properties: {
        triggered: { type: "boolean" },
        expression: { type: "string" },
        trigger_type: { type: "string" },
      },
    },
  },
  {
    type: "decision_system.trigger_webhook",
    label: "Webhook Trigger",
    description: "Trigger a workflow via an HTTP webhook",
    icon: "🔗",
    color: "#4f46e5",
    categories: ["trigger"],
    config_schema: {
      type: "object",
      properties: {
        webhook_path: {
          type: "string", title: "Webhook Path",
          default: "my-webhook",
          description: "Unique path for the webhook endpoint",
        },
      },
    },
    input_schema: { type: "object", properties: { payload: { type: "object" } } },
    output_schema: {
      type: "object",
      properties: {
        triggered: { type: "boolean" },
        webhook_path: { type: "string" },
      },
    },
  },
  {
    type: "decision_system.trigger_file_watch",
    label: "File Watch Trigger",
    description: "Trigger a workflow when new files appear in a directory",
    icon: "👁️",
    color: "#8b5cf6",
    categories: ["trigger"],
    config_schema: {
      type: "object",
      properties: {
        directory: { type: "string", title: "Directory", default: "/tmp/watch", description: "Directory to watch" },
        pattern: { type: "string", title: "File Pattern", default: "*.csv", description: "Glob pattern to match" },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: {
      type: "object",
      properties: {
        triggered: { type: "boolean" },
        directory: { type: "string" },
        pattern: { type: "string" },
        _changed_files: { type: "array" },
      },
    },
  },
  // --- Phase 6: Specialist Agent Nodes ---
  {
    type: "decision_system.researcher",
    label: "Researcher",
    description: "Retrieve and synthesize information from connected data sources",
    icon: "📚",
    color: "#8b5cf6",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake" },
        max_sources: { type: "integer", title: "Max Sources", default: 5, minimum: 1, maximum: 50 },
        depth: { type: "string", title: "Research Depth", default: "balanced", enum: ["quick", "balanced", "deep"] },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Research question or topic" },
        context: { type: "string", description: "Additional context" },
      },
      required: ["query"],
    },
    output_schema: {
      type: "object",
      properties: {
        findings: { type: "array" },
        summary: { type: "string" },
        gaps: { type: "array" },
        fallback_reason: { type: "string" },
      },
    },
  },
  {
    type: "decision_system.critic",
    label: "Critic / Judge",
    description: "Review outputs for contradictions, unsupported claims, and logical fallacies",
    icon: "⚖️",
    color: "#c026d3",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake" },
        criteria: {
          type: "array", title: "Review Criteria",
          items: { type: "string", enum: ["contradictions", "unsupported_claims", "logical_fallacies", "confidence_calibration"] },
          default: ["contradictions", "unsupported_claims"],
        },
        strictness: { type: "string", title: "Strictness", default: "balanced", enum: ["lenient", "balanced", "strict"] },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        target_type: { type: "string", enum: ["claims_list", "report_text", "findings_list"] },
        target_data: { type: "object", description: "Data to review" },
      },
      required: ["target_data"],
    },
    output_schema: {
      type: "object",
      properties: {
        passed: { type: "boolean" },
        issues: { type: "array" },
        summary: { type: "string" },
        confidence_adjustment: { type: "number" },
        fallback_reason: { type: "string" },
      },
    },
  },
  {
    type: "decision_system.synthesizer",
    label: "Decision Synthesizer",
    description: "Synthesize multiple evidence streams into weighted decisions",
    icon: "🎯",
    color: "#a855f7",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake" },
        decision_framework: {
          type: "string", title: "Decision Framework", default: "weighted_matrix",
          enum: ["pros_cons", "weighted_matrix", "tiered_recommendation"],
        },
        max_options: { type: "integer", title: "Max Options", default: 5, minimum: 2, maximum: 10 },
        include_risks: { type: "boolean", title: "Include Risk Assessments", default: true },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        question: { type: "string", description: "Decision question" },
        evidence_streams: { type: "array", description: "Evidence sources to synthesize" },
        criteria: { type: "array", description: "Decision criteria with weights" },
      },
      required: ["question"],
    },
    output_schema: {
      type: "object",
      properties: {
        options: { type: "array" },
        recommendation: { type: "object" },
        trade_offs_summary: { type: "string" },
        fallback_reason: { type: "string" },
      },
    },
  },
  // --- Phase 2: Review Gate Node ---
  {
    type: "decision_system.review_gate",
    label: "Review Gate",
    description: "Pause the workflow for human review of intermediate results",
    icon: "👁️",
    color: "#f97316",
    categories: ["flow"],
    config_schema: {
      type: "object",
      properties: {
        require_notes: { type: "boolean", title: "Require Notes", default: true },
        allow_edit: { type: "boolean", title: "Allow Editing", default: true },
        timeout_hours: {
          type: "integer", title: "Timeout (hours)", default: 72,
          minimum: 1, maximum: 8760,
        },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        data: { type: "object", description: "Data requiring review" },
        instructions: { type: "string", description: "Review instructions/context" },
      },
      required: ["data"],
    },
    output_schema: {
      type: "object",
      properties: {
        approved: { type: "boolean" },
        review_notes: { type: "string" },
        modified_data: { type: "object" },
        status: { type: "string" },
      },
    },
  },
  // --- Phase 7: Data Analyst Node ---
  {
    type: "decision_system.data_analyst",
    label: "Data Analyst",
    description: "Analyze structured data — profiles, trends, anomalies, and correlations",
    icon: "📊",
    color: "#7c3aed",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        provider: { type: "string", title: "Provider", default: "fake" },
        analysis_type: {
          type: "string", title: "Analysis Type", default: "summary",
          enum: ["profile", "summary", "trend", "anomaly", "correlation"],
        },
        max_rows: { type: "integer", title: "Max Rows", default: 1000, minimum: 1, maximum: 100000 },
        include_charts: { type: "boolean", title: "Include Charts", default: false },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        data: { type: "array", items: { type: "object" }, description: "Structured data to analyze" },
        analysis_type: { type: "string", description: "Override analysis type" },
        columns: { type: "array", items: { type: "string" }, description: "Focus on specific columns" },
      },
      required: ["data"],
    },
    output_schema: {
      type: "object",
      properties: {
        analysis: { type: "object" },
        summary: { type: "string" },
        charts: { type: "object" },
        fallback_reason: { type: "string" },
      },
    },
  },
  // --- Feature Set B: New Specialist Nodes ---
  {
    type: "decision_system.planner",
    label: "Planner",
    description: "Generate structured step-by-step execution plans from goals",
    icon: "📋",
    color: "#0ea5e9",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        detail_level: {
          type: "string", title: "Detail Level", default: "detailed",
          enum: ["high_level", "detailed", "very_detailed"],
        },
        include_timeline: { type: "boolean", title: "Include Timeline", default: true },
        max_steps: { type: "integer", title: "Max Steps", default: 8, minimum: 2, maximum: 20 },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        goal: { type: "string", description: "The objective to plan for" },
        constraints: { type: "string", description: "Constraints or requirements" },
        context: { type: "string", description: "Additional context" },
      },
      required: ["goal"],
    },
    output_schema: {
      type: "object",
      properties: {
        plan: { type: "array", items: { type: "object" } },
        summary: { type: "string" },
        total_steps: { type: "integer" },
        estimated_duration: { type: "string" },
      },
    },
  },
  {
    type: "decision_system.auditor",
    label: "Auditor",
    description: "Review data for quality, completeness, and consistency",
    icon: "🔎",
    color: "#84cc16",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        audit_depth: {
          type: "string", title: "Audit Depth", default: "standard",
          enum: ["quick", "standard", "thorough"],
        },
        severity_threshold: {
          type: "string", title: "Severity Threshold", default: "medium",
          enum: ["low", "medium", "high"],
        },
        fail_on_issues: { type: "boolean", title: "Fail on Issues", default: false },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        data: { type: "object", description: "The data to audit" },
        audit_scope: {
          type: "array", items: { type: "string" },
          description: "Aspects to check (completeness, consistency, accuracy, timeliness)",
        },
        criteria: { type: "object", description: "Custom audit criteria" },
      },
      required: ["data"],
    },
    output_schema: {
      type: "object",
      properties: {
        passed: { type: "boolean" },
        score: { type: "number" },
        findings: { type: "array" },
        summary: { type: "string" },
        issues_found: { type: "integer" },
        recommendations: { type: "array" },
      },
    },
  },
  {
    type: "decision_system.compliance_checker",
    label: "Compliance Checker",
    description: "Check data against compliance rules and policies",
    icon: "🛡️",
    color: "#dc2626",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        framework: {
          type: "string", title: "Framework", default: "internal",
          enum: ["internal", "gdpr", "soc2", "hipaa", "custom"],
        },
        strict_mode: { type: "boolean", title: "Strict Mode", default: false },
        auto_remediate: { type: "boolean", title: "Auto Remediate", default: false },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        data: { type: "object", description: "Data to check for compliance" },
        rules: {
          type: "array", items: { type: "string" },
          description: "Compliance rules to check against",
        },
        framework: { type: "string", description: "Compliance framework override" },
      },
      required: ["data"],
    },
    output_schema: {
      type: "object",
      properties: {
        compliant: { type: "boolean" },
        violations: { type: "array" },
        risk_level: { type: "string" },
        summary: { type: "string" },
        score: { type: "number" },
        passed_checks: { type: "integer" },
        failed_checks: { type: "integer" },
      },
    },
  },
  {
    type: "decision_system.code_runner",
    label: "Code Runner",
    description: "Execute Python snippets with I/O variables and timeout (simulated)",
    icon: "⚙️",
    color: "#64748b",
    categories: ["flow"],
    config_schema: {
      type: "object",
      properties: {
        timeout_seconds: { type: "integer", title: "Timeout (s)", default: 10, minimum: 1, maximum: 60 },
        capture_stdout: { type: "boolean", title: "Capture Stdout", default: true },
        allow_file_access: { type: "boolean", title: "Allow File Access", default: false },
      },
    },
    input_schema: {
      type: "object",
      properties: {
        source_code: { type: "string", description: "Python code to execute" },
        inputs: { type: "object", description: "Input variables accessible to the code" },
        libraries: {
          type: "array", items: { type: "string" },
          description: "Additional libraries to import",
        },
      },
      required: ["source_code"],
    },
    output_schema: {
      type: "object",
      properties: {
        result: { type: "object" },
        stdout: { type: "string" },
        error: { type: "string" },
        execution_time_ms: { type: "number" },
        success: { type: "boolean" },
      },
    },
  },
  {
    type: "decision_system.contradiction_scan",
    label: "Contradiction Scan",
    description: "Scans workspace evidence for contradictions between claims.",
    icon: "\u26a1",
    color: "#dc2626",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        workspace_id: { type: "string", title: "Workspace ID" },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: { type: "object", properties: { contradictions: { type: "array" } } },
  },
  {
    type: "decision_system.evidence_search",
    label: "Evidence Search",
    description: "Searches workspace evidence using keyword or vector retrieval.",
    icon: "\ud83d\udd0d",
    color: "#2563eb",
    categories: ["data"],
    config_schema: {
      type: "object",
      properties: {
        workspace_id: { type: "string", title: "Workspace ID" },
        query: { type: "string", title: "Search Query" },
        max_results: { type: "integer", title: "Max Results", default: 10 },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: { type: "object", properties: { results: { type: "array" } } },
  },
  {
    type: "decision_system.verification_summary",
    label: "Verification Summary",
    description: "Generates verification summary for execution or workspace.",
    icon: "\ud83d\udcca",
    color: "#059669",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        workspace_id: { type: "string", title: "Workspace ID" },
      },
    },
    input_schema: { type: "object", properties: {} },
    output_schema: { type: "object", properties: { summary: { type: "object" } } },
  },
  {
    type: "decision_system.verify_claims_v2",
    label: "Claim Verifier v2",
    description: "Verifies claims against workspace evidence with supported/contradicted/unsupported/uncertain/needs_review statuses.",
    icon: "\u2705",
    color: "#059669",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        workspace_id: { type: "string", title: "Workspace ID" },
        provider: { type: "string", title: "Provider", default: "fake", enum: ["fake"] },
      },
    },
    input_schema: { type: "object", properties: { claims: { type: "array" } } },
    output_schema: { type: "object", properties: { verified_claims: { type: "array" } } },
  },
  {
    type: "decision_system.evidence_synthesis",
    label: "Evidence Synthesis",
    description: "Synthesizes evidence using AI, extracts claims, and optionally auto-verifies them.",
    icon: "\ud83e\udde0",
    color: "#7c3aed",
    categories: ["ai"],
    config_schema: {
      type: "object",
      properties: {
        workspace_id: { type: "string", title: "Workspace ID" },
        question: { type: "string", title: "Question / Objective" },
        synthesis_mode: { type: "string", title: "Mode", default: "summary", enum: ["summary", "risks", "opportunities", "claims", "report_outline"] },
        provider_id: { type: "string", title: "Provider" },
        model: { type: "string", title: "Model" },
        auto_verify: { type: "boolean", title: "Auto-Verify", default: false },
      },
    },
    input_schema: { type: "object", properties: { evidence_results: { type: "array" } } },
    output_schema: { type: "object", properties: { synthesis_id: { type: "string" }, summary_text: { type: "string" }, claim_ids: { type: "array" } } },
  },
];

const MOCK_WORKFLOWS = [
  {
    id: "wf-sample-1",
    name: "Quarterly Risk Review",
    description: "Analyze company data and generate a risk report",
    nodes: [
      { id: "node-1", type: "decision_system.trigger_manual", label: "Start", config: {}, error_policy: "fail_workflow" },
      { id: "node-2", type: "decision_system.input_text", label: "Business Question", config: { text: "Where are we losing money?" }, error_policy: "fail_workflow" },
      { id: "node-3", type: "decision_system.retrieve", label: "Retrieve Evidence", config: { collection: "company_docs", top_k: 5 }, error_policy: "fail_workflow" },
      { id: "node-4", type: "decision_system.technical_analyst", label: "Tech Analysis", config: { provider: "fake" }, error_policy: "fail_workflow" },
      { id: "node-5", type: "decision_system.risk_analyst", label: "Risk Analysis", config: { provider: "fake" }, error_policy: "fail_workflow" },
      { id: "node-6", type: "decision_system.extract_claims", label: "Extract Claims", config: { provider: "fake" }, error_policy: "fail_workflow" },
      { id: "node-7", type: "decision_system.write_report", label: "Generate Report", config: { format: "markdown", provider: "fake" }, error_policy: "fail_workflow" },
    ],
    connections: [
      { source_node: "node-1", source_output: "default", target_node: "node-2", target_input: "default" },
      { source_node: "node-2", source_output: "default", target_node: "node-3", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-4", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-5", target_input: "default" },
      { source_node: "node-4", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-5", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-6", source_output: "default", target_node: "node-7", target_input: "default" },
    ],
    created_at: "2026-06-12T00:00:00Z",
    updated_at: "2026-06-12T00:00:00Z",
  },
  {
    id: "wf-sample-2",
    name: "Strategic Decision Demo",
    description: "Investment expansion analysis with researcher, critic, and synthesizer",
    nodes: [
      { id: "node-8", type: "decision_system.trigger_manual", label: "Start", config: {}, error_policy: "fail_workflow" },
      { id: "node-9", type: "decision_system.input_text", label: "Investment Question", config: { text: "Should we invest in expansion?" }, error_policy: "fail_workflow" },
      { id: "node-10", type: "decision_system.researcher", label: "Researcher", config: { provider: "fake", depth: "deep" }, error_policy: "fail_workflow" },
      { id: "node-11", type: "decision_system.critic", label: "Critic / Judge", config: { provider: "fake", criteria: ["contradictions", "unsupported_claims"], strictness: "balanced" }, error_policy: "fail_workflow" },
      { id: "node-review-1", type: "decision_system.review_gate", label: "Review Gate", config: { require_notes: true, allow_edit: true, timeout_hours: 72 }, error_policy: "fail_workflow" },
      { id: "node-12", type: "decision_system.synthesizer", label: "Decision Synthesizer", config: { provider: "fake", decision_framework: "weighted_matrix", max_options: 3 }, error_policy: "fail_workflow" },
    ],
    connections: [
      { source_node: "node-8", source_output: "default", target_node: "node-9", target_input: "default" },
      { source_node: "node-9", source_output: "default", target_node: "node-10", target_input: "default" },
      { source_node: "node-10", source_output: "default", target_node: "node-11", target_input: "default" },
      { source_node: "node-11", source_output: "default", target_node: "node-review-1", target_input: "default" },
      { source_node: "node-review-1", source_output: "default", target_node: "node-12", target_input: "default" },
    ],
    created_at: "2026-06-13T00:00:00Z",
    updated_at: "2026-06-13T00:00:00Z",
  },
];

const MOCK_EXECUTION_STATE = {
  execution_id: "exec-mock-1",
  workflow_id: "wf-sample-1",
  status: "running",
  node_states: {},
  started_at: "2026-06-12T00:00:00Z",
  completed_at: null,
  error: null,
};

const MOCK_EXECUTION_EVENTS = [
  { event_type: "node_started", node_id: "node-1", data: { node_type: "decision_system.trigger_manual" } },
  { event_type: "node_completed", node_id: "node-1", data: { outputs: { triggered: true } } },
  { event_type: "node_started", node_id: "node-2", data: { node_type: "decision_system.input_text" } },
  { event_type: "node_completed", node_id: "node-2", data: { outputs: { text: "Where are we losing money?" } } },
  { event_type: "node_started", node_id: "node-3", data: { node_type: "decision_system.retrieve" } },
  { event_type: "node_completed", node_id: "node-3", data: { outputs: { chunks: [] } } },
  { event_type: "node_started", node_id: "node-4", data: { node_type: "decision_system.technical_analyst" } },
  { event_type: "node_completed", node_id: "node-4", data: { outputs: { analysis: { summary: "Mock analysis" } } } },
  { event_type: "node_started", node_id: "node-5", data: { node_type: "decision_system.risk_analyst" } },
  { event_type: "node_completed", node_id: "node-5", data: { outputs: { risks: [] } } },
  { event_type: "workflow_completed", node_id: null, data: { status: "completed" } },
];

const MOCK_EXECUTION_STATE_2 = {
  execution_id: "exec-mock-2",
  workflow_id: "wf-sample-2",
  status: "completed",
  node_states: {},
  started_at: "2026-06-13T00:00:00Z",
  completed_at: "2026-06-13T00:00:00Z",
  error: null,
};

const MOCK_EXECUTION_EVENTS_2 = [
  { event_type: "node_started", node_id: "node-8", data: { node_type: "decision_system.trigger_manual" } },
  { event_type: "node_completed", node_id: "node-8", data: { outputs: { triggered: true } } },
  { event_type: "node_started", node_id: "node-9", data: { node_type: "decision_system.input_text" } },
  { event_type: "node_completed", node_id: "node-9", data: { outputs: { text: "Should we invest in expansion?" } } },
  { event_type: "node_started", node_id: "node-10", data: { node_type: "decision_system.researcher" } },
  {
    event_type: "node_completed", node_id: "node-10", data: {
      outputs: {
        findings: [
          {
            statement: "Revenue growth is projected at 15% YoY",
            confidence: 0.8,
            citation: "Q2 Financial Report 2026",
            evidence: ["Revenue trends show consistent growth across all segments"],
            source_type: "financial",
          },
          {
            statement: "Market expansion would require $500M initial investment",
            confidence: 0.6,
            citation: "Market Analysis Q1 2026",
            evidence: ["Industry benchmarks suggest $400-600M range for similar scale"],
            source_type: "market",
          },
          {
            statement: "Current cash reserves are insufficient for aggressive expansion",
            confidence: 0.85,
            citation: "Balance Sheet Q2 2026",
            evidence: ["Cash and equivalents total $120M, short-term investments $80M"],
            source_type: "financial",
          },
        ],
        summary: "Research complete on expansion viability",
        gaps: ["Detailed competitor expansion costs not available"],
        fallback_reason: null,
      },
    },
  },
  { event_type: "node_started", node_id: "node-11", data: { node_type: "decision_system.critic" } },
  {
    event_type: "node_completed", node_id: "node-11", data: {
      outputs: {
        passed: false,
        issues: [
          {
            type: "contradiction",
            severity: "high",
            description: "Finding 2 claims $500M investment needed but Finding 3 shows only $200M in available capital — insufficient funds for the proposed expansion scale",
            location: "Claim 2",
            suggestion: "Reconcile funding requirements with available capital; consider phased approach or external financing",
          },
          {
            type: "unsupported",
            severity: "medium",
            description: "Finding 2 relies on limited data sources; the $400-600M benchmark range comes from a single industry report",
            location: "Claim 2",
            suggestion: "Gather additional market analysis reports to corroborate investment estimates",
          },
        ],
        summary: "Found 1 critical contradiction and 1 unsupported claim",
        confidence_adjustment: -0.1,
        fallback_reason: null,
      },
    },
  },
  { event_type: "node_started", node_id: "node-review-1", data: { node_type: "decision_system.review_gate" } },
  { event_type: "node_completed", node_id: "node-review-1", data: { outputs: { status: "pending_review", review_id: "review-mock-1", data: { findings: [] }, instructions: "Review findings before synthesis", created_at: "2026-06-13T10:00:00Z" } } },
  { event_type: "node_started", node_id: "node-12", data: { node_type: "decision_system.synthesizer" } },
  {
    event_type: "node_completed", node_id: "node-12", data: {
      outputs: {
        options: [
          { name: "Phased Expansion", description: "Expand in stages over 24 months, using operating cash flow to fund each phase", pros: ["Lower risk", "Uses existing cash flow"], cons: ["Slower time to market"], weight: 0.85 },
          { name: "Seek External Financing", description: "Pursue venture capital or strategic partner to fund full expansion", pros: ["Full expansion possible", "Faster timeline"], cons: ["Dilution", "Loss of control"], weight: 0.65 },
          { name: "Delay Expansion", description: "Delay expansion for 12-18 months to build cash reserves", pros: ["No external dependency", "Preserves flexibility"], cons: ["Missed market opportunity"], weight: 0.5 },
        ],
        recommendation: { name: "Phased Expansion", rationale: "Best balance of risk and opportunity given current cash constraints" },
        trade_offs_summary: "Higher risk options require external financing which introduces dilution risk",
        fallback_reason: null,
      },
    },
  },
  { event_type: "workflow_completed", node_id: null, data: { status: "completed" } },
];

const MOCK_SCHEDULES = [
  {
    id: "sch-mock-001",
    workflow_id: "wf-sample-1",
    trigger_type: "cron",
    trigger_config: { expression: "0 9 * * 1", _node_id: "cron-1" },
    enabled: true,
    last_fired: null,
    created_at: "2026-06-12T00:00:00Z",
    updated_at: "2026-06-12T00:00:00Z",
  },
];

const MOCK_PROVIDERS = [
  {
    name: "opencode",
    api_base: "https://opencode.ai/zen/v1",
    api_key_configured: false,
    default_model: "claude-sonnet-4-20250514",
  },
  {
    name: "openai",
    api_base: "https://api.openai.com/v1",
    api_key_configured: false,
    default_model: "gpt-4o",
  },
];

const MOCK_REVIEWS = [
  {
    id: "review-mock-1",
    review_id: "review-mock-1",
    workflow_id: "wf-sample-2",
    execution_id: "exec-mock-2",
    node_id: "node-review-1",
    status: "pending_review",
    data: {
      findings: [
        {
          statement: "Revenue growth is projected at 15% YoY",
          confidence: 0.8,
          citation: "Q2 Financial Report 2026",
          source_type: "financial",
        },
        {
          statement: "Market expansion would require $500M initial investment",
          confidence: 0.6,
          citation: "Market Analysis Q1 2026",
          source_type: "market",
        },
        {
          statement: "Current cash reserves are insufficient for aggressive expansion",
          confidence: 0.85,
          citation: "Balance Sheet Q2 2026",
          source_type: "financial",
        },
      ],
    },
    instructions: "Review these research findings for accuracy and completeness before proceeding with business decision.",
    reviewers: [],
    created_at: "2026-06-13T10:00:00Z",
    resolved_at: null,
    action: null,
    review_notes: null,
    modified_data: null,
    reviewed_by: null,
  },
];

const MOCK_EXECUTION_HISTORY = [
  {
    id: "exec-hist-1",
    workflow_id: "wf-sample-1",
    workflow_name: "Quarterly Risk Review",
    status: "completed",
    started_at: "2026-06-12T09:00:00Z",
    completed_at: "2026-06-12T09:00:12Z",
    duration_ms: 12340,
    node_count: 7,
    completed_nodes: 7,
    failed_nodes: 0,
    claim_summary: { verified: 3, unsupported: 1, contradicted: 0, pending: 0, total: 4 },
  },
  {
    id: "exec-hist-2",
    workflow_id: "wf-sample-1",
    workflow_name: "Quarterly Risk Review",
    status: "completed",
    started_at: "2026-06-11T14:00:00Z",
    completed_at: "2026-06-11T14:00:08Z",
    duration_ms: 8420,
    node_count: 7,
    completed_nodes: 6,
    failed_nodes: 1,
    claim_summary: { verified: 2, unsupported: 2, contradicted: 0, pending: 0, total: 4 },
    error: "Node 'Risk Analysis' failed — timeout",
  },
  {
    id: "exec-hist-3",
    workflow_id: "wf-sample-2",
    workflow_name: "Strategic Decision Demo",
    status: "completed",
    started_at: "2026-06-10T11:30:00Z",
    completed_at: "2026-06-10T11:30:15Z",
    duration_ms: 15600,
    node_count: 5,
    completed_nodes: 5,
    failed_nodes: 0,
    claim_summary: { verified: 1, unsupported: 1, contradicted: 1, pending: 0, total: 3 },
  },
  {
    id: "exec-hist-4",
    workflow_id: "wf-sample-1",
    workflow_name: "Quarterly Risk Review",
    status: "failed",
    started_at: "2026-06-09T16:00:00Z",
    completed_at: "2026-06-09T16:00:05Z",
    duration_ms: 5300,
    node_count: 7,
    completed_nodes: 3,
    failed_nodes: 1,
    claim_summary: { verified: 0, unsupported: 0, contradicted: 0, pending: 0, total: 0 },
    error: "Node 'Extract Claims' failed — LLM provider unreachable",
  },
];

const MOCK_EXECUTION_DETAILS = {
  "exec-hist-1": {
    execution_id: "exec-hist-1",
    workflow_id: "wf-sample-1",
    workflow_name: "Quarterly Risk Review",
    status: "completed",
    started_at: "2026-06-12T09:00:00Z",
    completed_at: "2026-06-12T09:00:12Z",
    node_states: [
      { nodeId: "node-1", label: "Start", status: "completed", duration: 0.5 },
      { nodeId: "node-2", label: "Business Question", status: "completed", duration: 0.3 },
      { nodeId: "node-3", label: "Retrieve Evidence", status: "completed", duration: 2.1 },
      { nodeId: "node-4", label: "Tech Analysis", status: "completed", duration: 3.2 },
      { nodeId: "node-5", label: "Risk Analysis", status: "completed", duration: 2.8 },
      { nodeId: "node-6", label: "Extract Claims", status: "completed", duration: 1.9 },
      { nodeId: "node-7", label: "Generate Report", status: "completed", duration: 1.5 },
    ],
    claims: [
      { statement: "Revenue growth is projected at 15% YoY", status: "verified", confidence: 0.8, sourceNode: "Tech Analysis" },
      { statement: "Cloud migration costs will be $2.5M", status: "verified", confidence: 0.75, sourceNode: "Tech Analysis" },
      { statement: "Legacy system poses security risk", status: "verified", confidence: 0.9, sourceNode: "Risk Analysis" },
      { statement: "Competitor is gaining market share", status: "unsupported", confidence: 0.3, sourceNode: "Risk Analysis" },
    ],
  },
  "exec-hist-2": {
    execution_id: "exec-hist-2",
    workflow_id: "wf-sample-1",
    workflow_name: "Quarterly Risk Review",
    status: "completed",
    started_at: "2026-06-11T14:00:00Z",
    completed_at: "2026-06-11T14:00:08Z",
    node_states: [
      { nodeId: "node-1", label: "Start", status: "completed", duration: 0.4 },
      { nodeId: "node-2", label: "Business Question", status: "completed", duration: 0.3 },
      { nodeId: "node-3", label: "Retrieve Evidence", status: "completed", duration: 2.0 },
      { nodeId: "node-4", label: "Tech Analysis", status: "completed", duration: 2.9 },
      { nodeId: "node-5", label: "Risk Analysis", status: "failed", duration: 1.2, error: "Timeout" },
      { nodeId: "node-6", label: "Extract Claims", status: "skipped", duration: 0 },
      { nodeId: "node-7", label: "Generate Report", status: "skipped", duration: 0 },
    ],
    claims: [
      { statement: "Revenue growth is projected at 15% YoY", status: "verified", confidence: 0.8, sourceNode: "Tech Analysis" },
      { statement: "Cloud migration costs will be $2.5M", status: "verified", confidence: 0.75, sourceNode: "Tech Analysis" },
      { statement: "Legacy system poses security risk", status: "unsupported", confidence: 0.35, sourceNode: "Risk Analysis" },
      { statement: "Competitor is gaining market share", status: "unsupported", confidence: 0.3, sourceNode: "Risk Analysis" },
    ],
  },
};

// --- Verification Mock Data ---
const MOCK_CLAIM_VERIFICATION = {
  "claim-1": {
    claim_id: "claim-1",
    claim_text: "Revenue declined 15% in Q2 due to customer churn",
    claim_type: "metric",
    status: "supported",
    confidence: "high",
    evidence_quality: { label: "strong", score: 0.87, evidence_count: 3 },
    verification_method: "keyword_overlap",
    verification_reason: "Evidence supports revenue decline claim with matching metrics",
    verified_at: "2026-06-23T10:30:00Z",
    requires_review: false,
    evidence_count: 3,
    contradiction_count: 0,
    updated_at: "2026-06-23T10:30:00Z",
  },
  "claim-2": {
    claim_id: "claim-2",
    claim_text: "Customer satisfaction score is 92%",
    claim_type: "metric",
    status: "contradicted",
    confidence: "low",
    evidence_quality: { label: "contradicted", score: 0.45, evidence_count: 2 },
    verification_method: "keyword_overlap",
    verification_reason: "Evidence shows satisfaction score of 78%, contradicting 92% claim",
    verified_at: "2026-06-23T10:30:00Z",
    requires_review: true,
    evidence_count: 2,
    contradiction_count: 1,
    updated_at: "2026-06-23T10:30:00Z",
  },
  "claim-3": {
    claim_id: "claim-3",
    claim_text: "New product launch increased market share",
    claim_type: "outcome",
    status: "unsupported",
    confidence: "low",
    evidence_quality: { label: "weak", score: 0.32, evidence_count: 0 },
    verification_method: "keyword_overlap",
    verification_reason: "No evidence found to support market share increase claim",
    verified_at: "2026-06-23T10:30:00Z",
    requires_review: true,
    evidence_count: 0,
    contradiction_count: 0,
    updated_at: "2026-06-23T10:30:00Z",
  },
  "claim-4": {
    claim_id: "claim-4",
    claim_text: "Operating costs reduced by 10% through automation",
    claim_type: "metric",
    status: "uncertain",
    confidence: "medium",
    evidence_quality: { label: "moderate", score: 0.55, evidence_count: 1 },
    verification_method: "keyword_overlap",
    verification_reason: "Partial evidence found; automation mentioned but cost reduction figure unconfirmed",
    verified_at: "2026-06-23T10:30:00Z",
    requires_review: false,
    evidence_count: 1,
    contradiction_count: 0,
    updated_at: "2026-06-23T10:30:00Z",
  },
  "claim-5": {
    claim_id: "claim-5",
    claim_text: "Data breach exposed customer PII to unauthorized parties",
    claim_type: "risk",
    status: "needs_review",
    confidence: "medium",
    evidence_quality: { label: "moderate", score: 0.62, evidence_count: 2 },
    verification_method: "keyword_overlap",
    verification_reason: "High-risk claim with limited supporting evidence; manual review recommended",
    verified_at: "2026-06-23T10:30:00Z",
    requires_review: true,
    evidence_count: 2,
    contradiction_count: 0,
    updated_at: "2026-06-23T10:30:00Z",
  },
};

const MOCK_VERIFICATION_SUMMARY = {
  total_claims: 5,
  supported: 1,
  contradicted: 1,
  unsupported: 1,
  uncertain: 1,
  needs_review: 1,
  average_confidence: 0.56,
  evidence_coverage_score: 0.62,
  evidence_breakdown: {
    strong: 1,
    moderate: 2,
    weak: 1,
    missing: 0,
    contradicted: 1,
  },
  contradiction_count: 1,
  verified_at: "2026-06-23T10:30:00Z",
};

const MOCK_CONTRADICTIONS = [
  {
    id: "con-1",
    type: "metric_conflict",
    description: "Customer satisfaction score claim (92%) contradicts evidence (78%)",
    severity: "high",
    confidence: 0.92,
    claim_id: "claim-2",
    claim_text: "Customer satisfaction score is 92%",
    evidence_sources: ["Q2 report pg 12", "Customer survey results"],
    detected_at: "2026-06-23T10:30:00Z",
  },
  {
    id: "con-2",
    type: "risk_presence",
    description: "Revenue decline mentioned without corresponding risk assessment",
    severity: "medium",
    confidence: 0.68,
    claim_id: "claim-1",
    claim_text: "Revenue declined 15% in Q2 due to customer churn",
    evidence_sources: ["Financial summary Q2"],
    detected_at: "2026-06-23T10:30:00Z",
  },
];

const MOCK_TRUST_REPORT = {
  report_id: "rpt-1",
  workspace_id: "ws-1",
  execution_id: "exec-1",
  title: "Trust Report — Revenue Analysis Q2",
  generated_at: "2026-06-23T10:30:00Z",
  sections: [
    { id: "executive_summary", title: "Executive Summary", content: "Analysis of Q2 revenue data with 5 claims verified. 1 claim supported, 1 contradicted, 1 unsupported, 1 uncertain, 1 needs review. Overall evidence coverage score: 62%." },
    { id: "verification_summary", title: "Verification Summary", content: "{\"total_claims\":5,\"supported\":1,\"contradicted\":1,\"unsupported\":1,\"uncertain\":1,\"needs_review\":1,\"average_confidence\":0.56}" },
    { id: "supported_claims", title: "Supported Claims", content: "claim-1: Revenue declined 15% in Q2 due to customer churn — supported with strong evidence (score: 0.87)." },
    { id: "contradicted_claims", title: "Contradicted Claims", content: "claim-2: Customer satisfaction score is 92% — contradicted by evidence showing 78%." },
    { id: "unsupported_claims", title: "Unsupported Claims", content: "claim-3: New product launch increased market share — no supporting evidence found." },
    { id: "uncertain_claims", title: "Uncertain Claims", content: "claim-4: Operating costs reduced by 10% through automation — partial evidence only." },
    { id: "claims_needing_review", title: "Claims Needing Review", content: "claim-5: Data breach exposed customer PII — high-risk claim requiring manual review." },
    { id: "evidence_table", title: "Evidence Table", content: "| Claim | Status | Evidence Quality | Confidence |\\n|-------|--------|-----------------|------------|\\n| Revenue declined 15% | Supported | Strong | 0.87 |\\n| Satisfaction 92% | Contradicted | Contradicted | 0.45 |\\n| Market share increase | Unsupported | Weak | 0.32 |\\n| Cost reduction 10% | Uncertain | Moderate | 0.55 |\\n| Data breach | Needs Review | Moderate | 0.62 |" },
    { id: "contradictions", title: "Contradictions", content: "1 contradiction found: Customer satisfaction score conflict (severity: high)." },
    { id: "warnings_and_limitations", title: "Warnings and Limitations", content: "This verification is deterministic and conservative. It uses keyword overlap scoring, not semantic understanding. Unsupported claims may lack evidence due to incomplete indexing. The verifier is not a perfect truth engine." },
    { id: "recommended_next_actions", title: "Recommended Next Actions", content: "1. Review contradicted claim about satisfaction score. 2. Find supporting evidence for unsupported market share claim. 3. Conduct manual review of data breach claim. 4. Upload more evidence to improve coverage." },
  ],
  claims: Object.keys(MOCK_CLAIM_VERIFICATION).map(k => MOCK_CLAIM_VERIFICATION[k]),
  summary: { total_claims: 5, supported: 1, contradicted: 1, unsupported: 1, uncertain: 1, needs_review: 1, average_confidence: 0.56 },
  contradictions: [{ id: "con-1", type: "metric_conflict", description: "Customer satisfaction score claim (92%) contradicts evidence (78%)", severity: "high" }],
};

const MOCK_WORKFLOW_VERSIONS = [
  {
    id: "wf-ver-1",
    workflow_id: "wf-sample-1",
    version: 1,
    name: "Quarterly Risk Review v1",
    created_at: "2026-06-10T00:00:00Z",
    description: "Initial version with standard analysis pipeline",
    nodes: [
      { id: "node-1", type: "decision_system.trigger_manual", label: "Start", config: {} },
      { id: "node-2", type: "decision_system.input_text", label: "Business Question", config: { text: "Where are we losing money?" } },
      { id: "node-3", type: "decision_system.retrieve", label: "Retrieve Evidence", config: { collection: "company_docs", top_k: 5 } },
      { id: "node-4", type: "decision_system.technical_analyst", label: "Tech Analysis", config: { provider: "fake" } },
      { id: "node-5", type: "decision_system.risk_analyst", label: "Risk Analysis", config: { provider: "fake" } },
      { id: "node-6", type: "decision_system.extract_claims", label: "Extract Claims", config: { provider: "fake" } },
      { id: "node-7", type: "decision_system.write_report", label: "Generate Report", config: { format: "markdown", provider: "fake" } },
    ],
    connections: [
      { source_node: "node-1", source_output: "default", target_node: "node-2", target_input: "default" },
      { source_node: "node-2", source_output: "default", target_node: "node-3", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-4", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-5", target_input: "default" },
      { source_node: "node-4", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-5", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-6", source_output: "default", target_node: "node-7", target_input: "default" },
    ],
  },
  {
    id: "wf-ver-2",
    workflow_id: "wf-sample-1",
    version: 2,
    name: "Quarterly Risk Review v2",
    created_at: "2026-06-12T00:00:00Z",
    description: "Added confidence filter, increased top_k to 10",
    nodes: [
      { id: "node-1", type: "decision_system.trigger_manual", label: "Start", config: {} },
      { id: "node-2", type: "decision_system.input_text", label: "Business Question", config: { text: "Where are we losing money?" } },
      { id: "node-3", type: "decision_system.retrieve", label: "Retrieve Evidence", config: { collection: "company_docs", top_k: 10 } },
      { id: "node-4", type: "decision_system.technical_analyst", label: "Tech Analysis", config: { provider: "fake" } },
      { id: "node-5", type: "decision_system.risk_analyst", label: "Risk Analysis", config: { provider: "fake" } },
      { id: "node-6", type: "decision_system.extract_claims", label: "Extract Claims", config: { provider: "fake" } },
      { id: "node-7", type: "decision_system.filter", label: "Filter Results", config: { field: "confidence", operator: "greater_than", value: "0.5" } },
      { id: "node-8", type: "decision_system.write_report", label: "Generate Report", config: { format: "markdown", provider: "fake" } },
    ],
    connections: [
      { source_node: "node-1", source_output: "default", target_node: "node-2", target_input: "default" },
      { source_node: "node-2", source_output: "default", target_node: "node-3", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-4", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-5", target_input: "default" },
      { source_node: "node-4", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-5", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-6", source_output: "default", target_node: "node-7", target_input: "default" },
      { source_node: "node-7", source_output: "default", target_node: "node-8", target_input: "default" },
    ],
  },
  {
    id: "wf-sample-3",
    name: "AI-Assisted Evidence Synthesis",
    description: "Search evidence, synthesize with AI, verify claims, and generate trust report",
    nodes: [
      { id: "node-1", type: "decision_system.trigger_manual", label: "Start", config: {}, error_policy: "fail_workflow" },
      { id: "node-2", type: "decision_system.input_text", label: "Business Question", config: { text: "What are our key risks?" }, error_policy: "fail_workflow" },
      { id: "node-3", type: "decision_system.evidence_search", label: "Search Evidence", config: { workspace_id: "ws-1", max_results: 10 }, error_policy: "fail_workflow" },
      { id: "node-4", type: "decision_system.evidence_synthesis", label: "Synthesize Evidence", config: { synthesis_mode: "summary", auto_verify: true }, error_policy: "fail_workflow" },
      { id: "node-5", type: "decision_system.contradiction_scan", label: "Contradiction Scan", config: { workspace_id: "ws-1" }, error_policy: "fail_workflow" },
      { id: "node-6", type: "decision_system.review_gate", label: "Human Review", config: {}, error_policy: "pause_workflow" },
      { id: "node-7", type: "decision_system.write_report", label: "Generate Report", config: { format: "markdown" }, error_policy: "fail_workflow" },
    ],
    connections: [
      { source_node: "node-1", source_output: "default", target_node: "node-2", target_input: "default" },
      { source_node: "node-2", source_output: "default", target_node: "node-3", target_input: "default" },
      { source_node: "node-3", source_output: "default", target_node: "node-4", target_input: "default" },
      { source_node: "node-4", source_output: "default", target_node: "node-5", target_input: "default" },
      { source_node: "node-5", source_output: "default", target_node: "node-6", target_input: "default" },
      { source_node: "node-6", source_output: "default", target_node: "node-7", target_input: "default" },
    ],
  },
];

export {
  MOCK_NODE_TYPES,
  MOCK_WORKFLOWS,
  MOCK_EXECUTION_STATE,
  MOCK_EXECUTION_EVENTS,
  MOCK_EXECUTION_STATE_2,
  MOCK_EXECUTION_EVENTS_2,
  MOCK_SCHEDULES,
  MOCK_PROVIDERS,
  MOCK_REVIEWS,
  MOCK_EXECUTION_HISTORY,
  MOCK_EXECUTION_DETAILS,
  MOCK_CLAIM_VERIFICATION,
  MOCK_VERIFICATION_SUMMARY,
  MOCK_CONTRADICTIONS,
  MOCK_TRUST_REPORT,
  MOCK_WORKFLOW_VERSIONS,
};
