// nodeTypes.js — Converts API node types to visual configs
//
// Categories align with v1.22 productized workflow builder:
//   Core, Data, Evidence, AI, Verification, Review, Report, Utility

const CATEGORY_CONFIG = {
  core:        { color: "#3b82f6", bg: "#eff6ff", label: "Core",        icon: "⚡" },
  data:        { color: "#f59e0b", bg: "#fffbeb", label: "Data",        icon: "📊" },
  evidence:    { color: "#14b8a6", bg: "#f0fdfa", label: "Evidence",    icon: "🔍" },
  ai:          { color: "#8b5cf6", bg: "#f5f3ff", label: "AI",          icon: "🤖" },
  verification:{ color: "#22c55e", bg: "#f0fdf4", label: "Verification",icon: "✅" },
  review:      { color: "#f97316", bg: "#fff7ed", label: "Review",      icon: "🛡️" },
  report:      { color: "#06b6d4", bg: "#ecfeff", label: "Report",      icon: "📄" },
  utility:     { color: "#6b7280", bg: "#f9fafb", label: "Utility",     icon: "🔧" },
};

/**
 * Detailed node catalog with metadata for each node type.
 * Each entry includes: type, label, category, description,
 * required/optional fields, provider requirement, safety warning.
 */
const NODE_CATALOG = {
  "decision_system.trigger_manual": {
    type: "decision_system.trigger_manual",
    label: "Start",
    category: "core",
    description: "Start a workflow manually. Every workflow needs a Start node.",
    inputs: [],
    outputs: ["triggered"],
    required_fields: [],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.input_text": {
    type: "decision_system.input_text",
    label: "Manual Input",
    category: "core",
    description: "Provide text input for the workflow. No AI provider needed.",
    inputs: [],
    outputs: ["text"],
    required_fields: ["text"],
    optional_fields: ["label"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.cron_trigger": {
    type: "decision_system.cron_trigger",
    label: "Cron Trigger",
    category: "core",
    description: "Start a workflow on a schedule using cron expression.",
    inputs: [],
    outputs: ["triggered"],
    required_fields: ["cron_expression"],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.webhook_trigger": {
    type: "decision_system.webhook_trigger",
    label: "Webhook Trigger",
    category: "core",
    description: "Start a workflow via incoming webhook request.",
    inputs: [],
    outputs: ["payload"],
    required_fields: ["webhook_path"],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.file_watch_trigger": {
    type: "decision_system.file_watch_trigger",
    label: "File Watch Trigger",
    category: "core",
    description: "Start a workflow when a file changes in a watched directory.",
    inputs: [],
    outputs: ["triggered"],
    required_fields: ["watch_path"],
    optional_fields: ["file_pattern"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.retrieve": {
    type: "decision_system.retrieve",
    label: "Retrieve Evidence",
    category: "evidence",
    description: "Searches local workspace evidence. Does not require AI provider.",
    inputs: ["query"],
    outputs: ["chunks"],
    required_fields: ["collection", "top_k"],
    optional_fields: ["source_ids", "file_types"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.evidence_search": {
    type: "decision_system.evidence_search",
    label: "Evidence Search",
    category: "evidence",
    description: "Search workspace evidence by query. Does not require AI provider.",
    inputs: ["query"],
    outputs: ["results"],
    required_fields: ["workspace_id", "query"],
    optional_fields: ["limit", "source_ids", "file_types"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.evidence_synthesis": {
    type: "decision_system.evidence_synthesis",
    label: "Evidence Synthesis",
    category: "ai",
    description: "Uses configured provider to draft summaries/claims from evidence. Generated claims are pending until verified.",
    inputs: ["evidence"],
    outputs: ["synthesis", "claims"],
    required_fields: ["question", "synthesis_mode"],
    optional_fields: ["provider_id", "model", "auto_verify"],
    provider_required: true,
    safety_warning: "Generated claims are draft-quality until verified. Do not treat AI output as fact.",
  },
  "decision_system.technical_analyst": {
    type: "decision_system.technical_analyst",
    label: "Technical Analyst",
    category: "ai",
    description: "Analyze technical data and system information.",
    inputs: ["data"],
    outputs: ["analysis"],
    required_fields: [],
    optional_fields: ["provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.risk_analyst": {
    type: "decision_system.risk_analyst",
    label: "Risk Analyst",
    category: "ai",
    description: "Analyze risks and vulnerabilities from data.",
    inputs: ["data"],
    outputs: ["risks"],
    required_fields: [],
    optional_fields: ["provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.researcher": {
    type: "decision_system.researcher",
    label: "Researcher",
    category: "ai",
    description: "Retrieve and synthesize information from connected sources.",
    inputs: ["query"],
    outputs: ["findings"],
    required_fields: [],
    optional_fields: ["max_sources", "depth", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.critic": {
    type: "decision_system.critic",
    label: "Critic / Judge",
    category: "ai",
    description: "Review outputs for contradictions, unsupported claims, logical fallacies.",
    inputs: ["data"],
    outputs: ["issues"],
    required_fields: [],
    optional_fields: ["criteria", "strictness", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.synthesizer": {
    type: "decision_system.synthesizer",
    label: "Decision Synthesizer",
    category: "ai",
    description: "Combine multiple evidence/analysis streams into weighted decision options.",
    inputs: ["data"],
    outputs: ["options", "recommendation"],
    required_fields: [],
    optional_fields: ["decision_framework", "include_risks", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.data_analyst": {
    type: "decision_system.data_analyst",
    label: "Data Analyst",
    category: "ai",
    description: "Analyze structured data with profile, summary, trend, anomaly, correlation.",
    inputs: ["data"],
    outputs: ["analysis", "summary"],
    required_fields: [],
    optional_fields: ["analysis_type", "max_rows", "include_charts", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.extract_claims": {
    type: "decision_system.extract_claims",
    label: "Extract Claims",
    category: "ai",
    description: "Extract claims from analysis output.",
    inputs: ["text"],
    outputs: ["claims"],
    required_fields: [],
    optional_fields: ["supported_types", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.verify_claims": {
    type: "decision_system.verify_claims",
    label: "Verify Claims",
    category: "verification",
    description: "Verify extracted claims against local workspace evidence. Does not prove truth.",
    inputs: ["claims"],
    outputs: ["verified"],
    required_fields: ["workspace_id"],
    optional_fields: ["execution_id", "claim_ids"],
    provider_required: false,
    safety_warning: "Claims are verified against available local evidence only. Absence of contradiction does not prove truth.",
  },
  "decision_system.claim_verifier_v2": {
    type: "decision_system.claim_verifier_v2",
    label: "Claim Verifier v2",
    category: "verification",
    description: "Deterministic claim verification with evidence quality scoring.",
    inputs: ["claims"],
    outputs: ["verified"],
    required_fields: ["workspace_id"],
    optional_fields: ["execution_id", "claim_ids"],
    provider_required: false,
    safety_warning: "Verification is against available local evidence only.",
  },
  "decision_system.contradiction_scan": {
    type: "decision_system.contradiction_scan",
    label: "Contradiction Scan",
    category: "verification",
    description: "Scan claims for contradictions. Does not require AI provider.",
    inputs: ["claims"],
    outputs: ["contradictions"],
    required_fields: [],
    optional_fields: ["workspace_id"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.verification_summary": {
    type: "decision_system.verification_summary",
    label: "Verification Summary",
    category: "verification",
    description: "Generate summary of verification results.",
    inputs: ["verified", "contradictions"],
    outputs: ["summary"],
    required_fields: [],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.review_gate": {
    type: "decision_system.review_gate",
    label: "Review Gate",
    category: "review",
    description: "Pauses workflow until human approval/rejection with notes.",
    inputs: ["data"],
    outputs: ["approved", "rejected"],
    required_fields: ["instructions"],
    optional_fields: ["reviewers", "risk_level"],
    provider_required: false,
    safety_warning: "Workflow pauses at this node until a human reviews and approves.",
  },
  "decision_system.write_report": {
    type: "decision_system.write_report",
    label: "Write Report",
    category: "report",
    description: "Generate a decision report from verified claims.",
    inputs: ["claims"],
    outputs: ["report"],
    required_fields: [],
    optional_fields: ["format", "include_evidence", "include_contradictions"],
    provider_required: false,
    safety_warning: "Report quality depends on claim verification quality.",
  },
  "decision_system.planner": {
    type: "decision_system.planner",
    label: "Planner",
    category: "ai",
    description: "Break down a task into step-by-step plans.",
    inputs: ["objective"],
    outputs: ["plan"],
    required_fields: [],
    optional_fields: ["provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.auditor": {
    type: "decision_system.auditor",
    label: "Auditor",
    category: "ai",
    description: "Audit outputs for quality, completeness, and policy compliance.",
    inputs: ["data"],
    outputs: ["audit"],
    required_fields: [],
    optional_fields: ["criteria", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.compliance_checker": {
    type: "decision_system.compliance_checker",
    label: "Compliance Checker",
    category: "ai",
    description: "Check outputs against rules, policies, and compliance requirements.",
    inputs: ["data"],
    outputs: ["compliance"],
    required_fields: [],
    optional_fields: ["rules", "provider", "model"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.code_runner": {
    type: "decision_system.code_runner",
    label: "Code Runner",
    category: "utility",
    description: "Simulated code execution with I/O. Unsafe: only use in trusted environments.",
    inputs: ["code"],
    outputs: ["result"],
    required_fields: ["code"],
    optional_fields: ["timeout"],
    provider_required: false,
    safety_warning: "DANGER: This node can execute arbitrary code. Only enable if you trust the workflow source.",
  },
  "decision_system.code": {
    type: "decision_system.code",
    label: "Code Node",
    category: "utility",
    description: "Execute custom Python code in workflow. DISABLED by default for security.",
    inputs: ["data"],
    outputs: ["result"],
    required_fields: ["code"],
    optional_fields: ["packages"],
    provider_required: false,
    safety_warning: "DISABLED by default. Set DECISION_SYSTEM_ENABLE_UNSAFE_CODE_NODE=true to enable (unsafe).",
  },
  "decision_system.filter": {
    type: "decision_system.filter",
    label: "Filter",
    category: "utility",
    description: "Filter data based on conditions.",
    inputs: ["data"],
    outputs: ["filtered"],
    required_fields: ["condition"],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.merge": {
    type: "decision_system.merge",
    label: "Merge",
    category: "utility",
    description: "Merge multiple data streams into one.",
    inputs: ["data_a", "data_b"],
    outputs: ["merged"],
    required_fields: [],
    optional_fields: ["merge_key", "how"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.extract_graph": {
    type: "decision_system.extract_graph",
    label: "Extract Graph",
    category: "data",
    description: "Extract entities and relationships from text.",
    inputs: ["text"],
    outputs: ["graph"],
    required_fields: [],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.profile_data": {
    type: "decision_system.profile_data",
    label: "Profile Data",
    category: "data",
    description: "Profile structured data for statistics and quality metrics.",
    inputs: ["data"],
    outputs: ["profile"],
    required_fields: [],
    optional_fields: ["max_rows"],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.map_ontology": {
    type: "decision_system.map_ontology",
    label: "Map Ontology",
    category: "data",
    description: "Map data columns to ontology concepts.",
    inputs: ["data"],
    outputs: ["mapping"],
    required_fields: [],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.detect_patterns": {
    type: "decision_system.detect_patterns",
    label: "Detect Patterns",
    category: "data",
    description: "Detect patterns, risks, and vulnerabilities in data.",
    inputs: ["data"],
    outputs: ["patterns"],
    required_fields: [],
    optional_fields: [],
    provider_required: false,
    safety_warning: null,
  },
  "decision_system.war_room": {
    type: "decision_system.war_room",
    label: "War Room",
    category: "ai",
    description: "Run bounded war-cabinet agent context protocol.",
    inputs: ["question"],
    outputs: ["artifacts", "judgment"],
    required_fields: ["question"],
    optional_fields: ["roles"],
    provider_required: false,
    safety_warning: null,
  },
};

/**
 * Get category config by category id.
 * Falls back to utility if unknown.
 */
function getNodeCategoryConfig(categoryId) {
  const entry = CATEGORY_CONFIG[categoryId];
  return entry || CATEGORY_CONFIG.utility;
}

/**
 * Get all category configs as a list.
 */
function getCategories() {
  return Object.entries(CATEGORY_CONFIG).map(([key, cfg]) => ({
    id: key,
    ...cfg,
  }));
}

/**
 * Get the catalog entry for a node type.
 */
function getNodeCatalogEntry(type) {
  return NODE_CATALOG[type] || null;
}

/**
 * Determine the category for a node type.
 * Checks NODE_CATALOG first, then falls back to nodeType.categories[0].
 */
function resolveNodeCategory(nodeType) {
  const entry = NODE_CATALOG[nodeType.type];
  if (entry) return entry.category;
  return nodeType.categories?.[0] || "utility";
}

export {
  CATEGORY_CONFIG,
  NODE_CATALOG,
  getNodeCategoryConfig,
  getCategories,
  getNodeCatalogEntry,
  resolveNodeCategory,
};
