"""Node definitions — base classes, registry, and built-in node types."""

# Built-in imports
from decision_system.workflow_engine.nodes.builtin import (
    ClaimVerifierNode,
    CodeNode,
    ContradictionScanNode,
    CronTriggerNode,
    DetectPatternsNode,
    EvidenceSearchNode,
    EvidenceSynthesisNode,
    ExtractClaimsNode,
    ExtractGraphNode,
    FileWatchTriggerNode,
    FilterNode,
    GraphExtractionNodeV2,
    GraphSummaryNode,
    InputTextNode,
    ManualTriggerNode,
    MapOntologyNode,
    MergeNode,
    MetricExtractionNode,
    ProfileDataNode,
    RetrieveNode,
    RiskAnalystNode,
    RiskExtractionNode,
    TechAnalystNode,
    VerificationSummaryNode,
    VerifyClaimsNode,
    WarRoomNode,
    WebhookTriggerNode,
    WriteReportNode,
)
from decision_system.workflow_engine.nodes.registry import NodeRegistry
from decision_system.workflow_engine.nodes.specialist import (
    AuditorNode,
    CodeRunnerNode,
    ComplianceCheckerNode,
    CriticNode,
    DataAnalystNode,
    PlannerNode,
    ResearcherNode,
    ReviewGateNode,
    SynthesizerNode,
)


def create_default_registry() -> NodeRegistry:
    """Create a registry pre-populated with all built-in node types."""
    registry = NodeRegistry()
    for node_cls in _ALL_BUILTIN_NODES:
        registry.register(node_cls)
    return registry


_ALL_BUILTIN_NODES = [
    ManualTriggerNode,
    InputTextNode,
    CronTriggerNode,
    WebhookTriggerNode,
    FileWatchTriggerNode,
    FilterNode,
    MergeNode,
    CodeNode,
    RetrieveNode,
    TechAnalystNode,
    RiskAnalystNode,
    ExtractClaimsNode,
    VerifyClaimsNode,
    WriteReportNode,
    ExtractGraphNode,
    ProfileDataNode,
    MapOntologyNode,
    DetectPatternsNode,
    WarRoomNode,
    EvidenceSearchNode,
    ClaimVerifierNode,
    ContradictionScanNode,
    VerificationSummaryNode,
    EvidenceSynthesisNode,
    GraphExtractionNodeV2,
    RiskExtractionNode,
    MetricExtractionNode,
    GraphSummaryNode,
    ResearcherNode,
    CriticNode,
    SynthesizerNode,
    DataAnalystNode,
    ReviewGateNode,
    PlannerNode,
    AuditorNode,
    ComplianceCheckerNode,
    CodeRunnerNode,
]

__all__ = [
    "NodeRegistry",
    "create_default_registry",
    "ManualTriggerNode",
    "InputTextNode",
    "CronTriggerNode",
    "WebhookTriggerNode",
    "FileWatchTriggerNode",
    "FilterNode",
    "MergeNode",
    "CodeNode",
    "RetrieveNode",
    "TechAnalystNode",
    "RiskAnalystNode",
    "ExtractClaimsNode",
    "VerifyClaimsNode",
    "WriteReportNode",
    "ExtractGraphNode",
    "ProfileDataNode",
    "MapOntologyNode",
    "DetectPatternsNode",
    "WarRoomNode",
    "EvidenceSearchNode",
    "EvidenceSynthesisNode",
    "ResearcherNode",
    "CriticNode",
    "SynthesizerNode",
    "DataAnalystNode",
    "ReviewGateNode",
    "PlannerNode",
    "AuditorNode",
    "ComplianceCheckerNode",
    "CodeRunnerNode",
]
