"""Workspace snapshot diff tool — compare two workspace exports side by side.

Operates on workspace export JSON files (generated by ``export-workspace``).
Produces structured diff results showing added, removed, and changed items
across documents, ontology mappings, insights, metrics, and security posture.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class DiffResult:
    """Structured diff between two workspace snapshots."""

    added_documents: list[str] = field(default_factory=list)
    removed_documents: list[str] = field(default_factory=list)
    changed_documents: list[str] = field(default_factory=list)

    added_ontology_items: list[str] = field(default_factory=list)
    removed_ontology_items: list[str] = field(default_factory=list)
    changed_ontology_items: list[str] = field(default_factory=list)

    added_insights: list[dict[str, Any]] = field(default_factory=list)
    removed_insights: list[dict[str, Any]] = field(default_factory=list)
    changed_insights: list[dict[str, Any]] = field(default_factory=list)

    added_metrics: list[dict[str, Any]] = field(default_factory=list)
    removed_metrics: list[dict[str, Any]] = field(default_factory=list)
    changed_metrics: list[dict[str, Any]] = field(default_factory=list)

    security_changes: list[str] = field(default_factory=list)
    summary: str = ""
    has_changes: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "added_documents": self.added_documents,
            "removed_documents": self.removed_documents,
            "changed_documents": self.changed_documents,
            "added_ontology_items": self.added_ontology_items,
            "removed_ontology_items": self.removed_ontology_items,
            "changed_ontology_items": self.changed_ontology_items,
            "added_insights": self.added_insights,
            "removed_insights": self.removed_insights,
            "changed_insights": self.changed_insights,
            "added_metrics": self.added_metrics,
            "removed_metrics": self.removed_metrics,
            "changed_metrics": self.changed_metrics,
            "security_changes": self.security_changes,
            "summary": self.summary,
            "has_changes": self.has_changes,
        }


def _load_export(path: Path) -> dict[str, Any]:
    """Load a workspace export JSON file."""
    raw = path.read_text(encoding="utf-8")
    return json.loads(raw)


def _extract_document_titles(export: dict[str, Any]) -> set[str]:
    """Extract document titles from a workspace export."""
    titles: set[str] = set()
    for art in export.get("artifacts", []):
        source = art.get("source_path", "") or ""
        if source:
            titles.add(source)
        title = art.get("title", "") or ""
        if title:
            titles.add(title)
    return titles


def _extract_ontology_concepts(export: dict[str, Any]) -> set[str]:
    """Extract ontology concept IDs from a workspace export."""
    concepts: set[str] = set()
    for art in export.get("artifacts", []):
        if art.get("artifact_type") == "ontology_map":
            content = art.get("content", {}) or {}
            for mapping in content.get("column_mappings", []):
                concept = mapping.get("concept_id", "")
                if concept:
                    concepts.add(concept)
            for concept in content.get("concepts", []):
                if isinstance(concept, dict):
                    cid = concept.get("concept_id", "") or ""
                    if cid:
                        concepts.add(cid)
                elif isinstance(concept, str):
                    concepts.add(concept)
    return concepts


def _extract_insights(export: dict[str, Any]) -> list[dict[str, Any]]:
    """Extract insight summaries from a workspace export."""
    insights: list[dict[str, Any]] = []
    for art in export.get("artifacts", []):
        if art.get("artifact_type") in ("insight_store", "insight"):
            content = art.get("content", {}) or {}
            raw_insights = content.get("insights", [])
            for ins in raw_insights:
                insights.append(
                    {
                        "title": ins.get("title", ""),
                        "severity": ins.get("severity", "unknown"),
                        "category": ins.get("category", "unknown"),
                    }
                )
    return insights


def _extract_metrics(export: dict[str, Any]) -> list[dict[str, Any]]:
    """Extract metrics from a workspace export."""
    metrics: list[dict[str, Any]] = []
    for art in export.get("artifacts", []):
        meta = art.get("metadata", {}) or {}
        for key in ("metrics", "stats", "counts"):
            value = meta.get(key)
            if value and isinstance(value, dict):
                metrics.append({key: value})
    return metrics


def _extract_security_info(export: dict[str, Any]) -> set[str]:
    """Extract security-related artifact summaries."""
    info: set[str] = set()
    for art in export.get("artifacts", []):
        atype = art.get("artifact_type", "")
        if "audit" in atype or "security" in atype or "policy" in atype:
            info.add(f"{atype}: {art.get('title', '')}")
    return info


def diff_workspaces(old_path: str | Path, new_path: str | Path) -> DiffResult:
    """Compare two workspace export files and return a structured diff."""
    old = _load_export(Path(old_path))
    new = _load_export(Path(new_path))

    result = DiffResult()

    # Documents
    old_docs = _extract_document_titles(old)
    new_docs = _extract_document_titles(new)
    result.added_documents = sorted(new_docs - old_docs)
    result.removed_documents = sorted(old_docs - new_docs)
    common_docs = old_docs & new_docs
    # Track changed documents: those with different metadata
    old_meta = {art.get("source_path", ""): art for art in old.get("artifacts", [])}
    new_meta = {art.get("source_path", ""): art for art in new.get("artifacts", [])}
    for doc in common_docs:
        old_content = old_meta.get(doc, {}).get("content")
        new_content = new_meta.get(doc, {}).get("content")
        if old_content != new_content:
            result.changed_documents.append(doc)

    # Ontology
    old_ont = _extract_ontology_concepts(old)
    new_ont = _extract_ontology_concepts(new)
    result.added_ontology_items = sorted(new_ont - old_ont)
    result.removed_ontology_items = sorted(old_ont - new_ont)
    if old_ont & new_ont:
        result.changed_ontology_items = sorted(old_ont & new_ont)

    # Insights
    old_ins = _extract_insights(old)
    new_ins = _extract_insights(new)
    old_ins_set = {i["title"] for i in old_ins}
    new_ins_set = {i["title"] for i in new_ins}
    result.added_insights = [i for i in new_ins if i["title"] not in old_ins_set]
    result.removed_insights = [i for i in old_ins if i["title"] not in new_ins_set]
    result.changed_insights = [
        {"title": t, "reason": "severity or category changed"} for t in (old_ins_set & new_ins_set)
    ]

    # Metrics
    old_metrics = _extract_metrics(old)
    new_metrics = _extract_metrics(new)
    result.added_metrics = (
        new_metrics[len(old_metrics) :] if len(new_metrics) > len(old_metrics) else []
    )
    result.removed_metrics = (
        old_metrics[len(new_metrics) :] if len(old_metrics) > len(new_metrics) else []
    )
    if old_metrics and new_metrics and old_metrics != new_metrics:
        result.changed_metrics = [m for m in new_metrics if m not in old_metrics]

    # Security
    old_sec = _extract_security_info(old)
    new_sec = _extract_security_info(new)
    if old_sec != new_sec:
        added = new_sec - old_sec
        removed = old_sec - new_sec
        if added:
            result.security_changes.append(f"Added: {', '.join(sorted(added))}")
        if removed:
            result.security_changes.append(f"Removed: {', '.join(sorted(removed))}")

    # Summary
    total_changes = (
        len(result.added_documents)
        + len(result.removed_documents)
        + len(result.changed_documents)
        + len(result.added_ontology_items)
        + len(result.removed_ontology_items)
        + len(result.changed_ontology_items)
        + len(result.added_insights)
        + len(result.removed_insights)
        + len(result.changed_insights)
        + len(result.added_metrics)
        + len(result.removed_metrics)
        + len(result.changed_metrics)
        + len(result.security_changes)
    )
    result.has_changes = total_changes > 0
    result.summary = (
        f"{total_changes} change(s): "
        f"{len(result.added_documents)} doc(s) added, "
        f"{len(result.removed_documents)} doc(s) removed, "
        f"{len(result.added_ontology_items)} ontology item(s) added, "
        f"{len(result.removed_ontology_items)} ontology item(s) removed, "
        f"{len(result.added_insights)} insight(s) added, "
        f"{len(result.security_changes)} security change(s)"
    )

    return result


def diff_to_text(result: DiffResult) -> str:
    """Render a DiffResult as human-readable text."""
    lines = ["# Workspace Diff", "", result.summary, ""]

    if result.added_documents:
        lines.extend(["## Added Documents", ""] + [f"- {d}" for d in result.added_documents] + [""])
    if result.removed_documents:
        lines.extend(
            ["## Removed Documents", ""] + [f"- {d}" for d in result.removed_documents] + [""]
        )
    if result.changed_documents:
        lines.extend(
            ["## Changed Documents", ""] + [f"- {d}" for d in result.changed_documents] + [""]
        )
    if result.added_ontology_items:
        lines.extend(
            ["## Added Ontology Items", ""] + [f"- {o}" for o in result.added_ontology_items] + [""]
        )
    if result.removed_ontology_items:
        lines.extend(
            ["## Removed Ontology Items", ""]
            + [f"- {o}" for o in result.removed_ontology_items]
            + [""]
        )
    if result.changed_ontology_items:
        lines.extend(
            ["## Changed Ontology Items", ""]
            + [f"- {o}" for o in result.changed_ontology_items]
            + [""]
        )
    if result.added_insights:
        lines.extend(
            ["## Added Insights", ""]
            + [f"- {i['title']} ({i['severity']})" for i in result.added_insights]
            + [""]
        )
    if result.removed_insights:
        lines.extend(
            ["## Removed Insights", ""]
            + [f"- {i['title']} ({i['severity']})" for i in result.removed_insights]
            + [""]
        )
    if result.security_changes:
        lines.extend(
            ["## Security Posture Changes", ""] + [f"- {s}" for s in result.security_changes] + [""]
        )

    if not result.has_changes:
        lines.append("No changes detected between the two snapshots.")

    return "\n".join(lines)
